language: java
jdk:
  - openjdk8

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

defore_deploy:
  - zip -r aws-proejct-webservice *
  - mkdir -p deploy
  - mv aws-proejct-webservice.zip deploy/aws-proejct-webservice.zip
deploy:
  -  project: s3
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
     bucket: aws-project-build
     region: ap-northeast-2
     acl: private
     skip_cleanup: true
     local_dir: deploy
     wait-until-deployed: true

notifications:
  email:
    recipients:
      - osh4880@gmail.com